---
- name: Display RUNNING-CONFIG
  hosts: router
  gather_facts: false
  tasks:
    - name: Run Command show running-config
      cisco.ios.ios_command:
        commands:
          - 'show running-config'
      register: result

    - name: Display Running-config
      var: result
