---
- name: Backup Cisco Devices Configuration
  hosts: '{{ TARGET }}'
  gather_facts: false
  tasks:
    - name: Display le path de stockage de backup
      ansible.builtin.debug:
        var: inventory_hostname
        
    - name: récupérer la Running Config
      cisco.ios.ios_config:
        backup: true
        
